services: 

  frontend:                    # FRONTEND
    build: .                   # Собирает из Dockerfile
    container_name: art-museum-frontend
    ports:
      - "80:80"                # Сайт доступен на http://localhost
    restart: unless-stopped


  loki: 
    image: grafana/loki:latest
    container_name: loki